version: '3'

vars:
  INSTALL_DIR: '{{.INSTALL_DIR | default "/usr/local/bin"}}'
  PROJECT_DIR:
    sh: pwd

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build all packages
    cmds:
      - bun install
      - bun run build

  install:
    desc: Install kaban wrapper script to system
    deps: [build]
    cmds:
      - |
        WRAPPER='#!/bin/bash
        exec bun run "{{.PROJECT_DIR}}/packages/cli/src/index.ts" "$@"'
        if [ -w "{{.INSTALL_DIR}}" ]; then
          echo "$WRAPPER" > "{{.INSTALL_DIR}}/kaban"
          chmod +x "{{.INSTALL_DIR}}/kaban"
        else
          echo "$WRAPPER" | sudo tee "{{.INSTALL_DIR}}/kaban" > /dev/null
          sudo chmod +x "{{.INSTALL_DIR}}/kaban"
        fi
        echo "Installed kaban to {{.INSTALL_DIR}}"
        echo "Note: Requires bun and project at {{.PROJECT_DIR}}"

  uninstall:
    desc: Remove kaban from system
    cmds:
      - |
        if [ -w "{{.INSTALL_DIR}}" ]; then
          rm -f "{{.INSTALL_DIR}}/kaban"
        else
          sudo rm -f "{{.INSTALL_DIR}}/kaban"
        fi
      - echo "Uninstalled kaban from {{.INSTALL_DIR}}"

  update:
    desc: Rebuild and reinstall
    cmds:
      - task: install

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf packages/*/dist
      - echo "Cleaned build artifacts"

  dev:cli:
    desc: Run CLI in development mode
    dir: packages/cli
    cmds:
      - bun run dev

  dev:tui:
    desc: Run TUI in development mode
    dir: packages/tui
    cmds:
      - bun run dev

  test:
    desc: Run all tests
    cmds:
      - bun run test

  typecheck:
    desc: Run type checking
    cmds:
      - bun run typecheck

  lint:
    desc: Run linter
    cmds:
      - bun run lint

  format:
    desc: Format code
    cmds:
      - bun run format
