//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult } from "@zenstackhq/orm";
export type boards = $ModelResult<$Schema, "boards">;
export type columns = $ModelResult<$Schema, "columns">;
export type tasks = $ModelResult<$Schema, "tasks">;
export type task_links = $ModelResult<$Schema, "task_links">;
export type audits = $ModelResult<$Schema, "audits">;
